name: uniconnecta
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_core_web: ^2.10.0
  image_picker: ^1.1.2
  http: ^1.2.2
  cloud_firestore: ^5.4.3
  url_launcher: ^6.1.8
  flutter_local_notifications: ^17.2.3
  firebase_storage: ^12.3.2
  intl: ^0.19.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  # Example for custom fonts:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
