// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdAhqWTObL_vbzJcr_c95wugfnlY9W6OY',
    appId: '1:333711271603:web:cab652b764d679c2fd72c6',
    messagingSenderId: '333711271603',
    projectId: 'uniconnecta-98fcc',
    authDomain: 'uniconnecta-98fcc.firebaseapp.com',
    storageBucket: 'uniconnecta-98fcc.appspot.com',
    measurementId: 'G-LZ2HTD94K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8lxkzqKLpPI_imAj7RfbNU82Hv0T_Iw',
    appId: '1:333711271603:android:a602642c6246344bfd72c6',
    messagingSenderId: '333711271603',
    projectId: 'uniconnecta-98fcc',
    storageBucket: 'uniconnecta-98fcc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdAhqWTObL_vbzJcr_c95wugfnlY9W6OY',
    appId: '1:333711271603:web:462fefdb489f325afd72c6',
    messagingSenderId: '333711271603',
    projectId: 'uniconnecta-98fcc',
    authDomain: 'uniconnecta-98fcc.firebaseapp.com',
    storageBucket: 'uniconnecta-98fcc.appspot.com',
    measurementId: 'G-654H3V7HPP',
  );
}
